//! Generated file, do not edit by hand, see `crate/ra_tools/src/codegen`

// This file is automatically generated based on the file `./generated.rs.tera`
// when `cargo gen-syntax` is run Do not edit manually

//! This module contains auto-generated Rust AST. Like `SyntaxNode`s, AST nodes
//! are generic over ownership: `X<'a>` things are `Copy` references, `XNode`
//! are Arc-based. You can switch between the two variants using `.owned` and
//! `.borrowed` functions. Most of the code works with borrowed mode, and only
//! this mode has all AST accessors.

#![allow(clippy::enum_glob_use)]
use crate::{
    ast::{self, AstNode, AstToken},
    SyntaxKind::{self, *},
    SyntaxNode, SyntaxToken,
};

// ArgList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArgList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ArgList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, ARG_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ArgList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ArgList {
    pub fn args(&self) -> impl Iterator<Item = Expr> {
        super::children(self)
    }
}

// ArrayExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArrayExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ArrayExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, ARRAY_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ArrayExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ArrayExpr {
    pub fn exprs(&self) -> impl Iterator<Item = Expr> {
        super::children(self)
    }
}

// ArrayType

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ArrayType {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ArrayType {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, ARRAY_TYPE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ArrayType { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ArrayType {
    pub fn type_ref(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }
}

// Attribute

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Attribute {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Attribute {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, ATTRIBUTE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Attribute { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Attribute {
    pub fn path(&self) -> Option<Path> {
        super::child_opt(self)
    }

    pub fn arg_list(&self) -> Option<ArgList> {
        super::child_opt(self)
    }
}

// AttributeList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct AttributeList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for AttributeList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, ATTRIBUTE_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(AttributeList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl AttributeList {
    pub fn attributes(&self) -> impl Iterator<Item = Attribute> {
        super::children(self)
    }
}

// BinExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BinExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for BinExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, BIN_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(BinExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl BinExpr {}

// BindPat

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BindPat {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for BindPat {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, BIND_PAT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(BindPat { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for BindPat {}
impl BindPat {
    pub fn pat(&self) -> Option<Pat> {
        super::child_opt(self)
    }
}

// BlockExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BlockExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for BlockExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, BLOCK_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(BlockExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl BlockExpr {
    pub fn statements(&self) -> impl Iterator<Item = Stmt> {
        super::children(self)
    }

    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// BreakExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct BreakExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for BreakExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, BREAK_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(BreakExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl BreakExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// CallExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CallExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for CallExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, CALL_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(CallExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::ArgListOwner for CallExpr {}
impl CallExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// CastExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct CastExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for CastExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, CAST_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(CastExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl CastExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }

    pub fn type_ref(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }
}

// ChannelRecvExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ChannelRecvExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ChannelRecvExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, CHANNEL_RECV_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ChannelRecvExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ChannelRecvExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// ChannelSendExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ChannelSendExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ChannelSendExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, CHANNEL_SEND_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ChannelSendExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ChannelSendExpr {}

// ChildDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ChildDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ChildDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, CHILD_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ChildDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for ChildDef {}
impl ChildDef {
    pub fn supervisor_item_list(&self) -> Option<SupervisorItemList> {
        super::child_opt(self)
    }
}

// ComptimeExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ComptimeExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ComptimeExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, COMPTIME_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ComptimeExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ComptimeExpr {
    pub fn body(&self) -> Option<BlockExpr> {
        super::child_opt(self)
    }
}

// Condition

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Condition {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Condition {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, CONDITION)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Condition { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Condition {
    pub fn pat(&self) -> Option<Pat> {
        super::child_opt(self)
    }

    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// EffectDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EffectDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for EffectDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, EFFECT_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(EffectDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for EffectDef {}
impl ast::VisibilityOwner for EffectDef {}
impl ast::DocCommentsOwner for EffectDef {}
impl ast::AttributeOwner for EffectDef {}
impl EffectDef {
    pub fn effect_op_list(&self) -> Option<EffectOpList> {
        super::child_opt(self)
    }
}

// EffectOp

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EffectOp {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for EffectOp {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, EFFECT_OP)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(EffectOp { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for EffectOp {}
impl EffectOp {
    pub fn param_list(&self) -> Option<ParamList> {
        super::child_opt(self)
    }

    pub fn ret_type(&self) -> Option<RetType> {
        super::child_opt(self)
    }
}

// EffectOpList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EffectOpList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for EffectOpList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, EFFECT_OP_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(EffectOpList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl EffectOpList {
    pub fn ops(&self) -> impl Iterator<Item = EffectOp> {
        super::children(self)
    }
}

// EnumDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EnumDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for EnumDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, ENUM_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(EnumDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for EnumDef {}
impl ast::VisibilityOwner for EnumDef {}
impl ast::DocCommentsOwner for EnumDef {}
impl ast::AttributeOwner for EnumDef {}
impl ast::GenericParamsOwner for EnumDef {}
impl EnumDef {
    pub fn enum_variant_list(&self) -> Option<EnumVariantList> {
        super::child_opt(self)
    }
}

// EnumVariant

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EnumVariant {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for EnumVariant {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, ENUM_VARIANT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(EnumVariant { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for EnumVariant {}
impl ast::DocCommentsOwner for EnumVariant {}
impl EnumVariant {
    pub fn record_field_def_list(&self) -> Option<RecordFieldDefList> {
        super::child_opt(self)
    }

    pub fn tuple_field_def_list(&self) -> Option<TupleFieldDefList> {
        super::child_opt(self)
    }
}

// EnumVariantList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct EnumVariantList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for EnumVariantList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, ENUM_VARIANT_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(EnumVariantList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl EnumVariantList {
    pub fn variants(&self) -> impl Iterator<Item = EnumVariant> {
        super::children(self)
    }
}

// Expr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Expr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Expr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            LITERAL
                | PREFIX_EXPR
                | PATH_EXPR
                | BIN_EXPR
                | CAST_EXPR
                | PAREN_EXPR
                | CALL_EXPR
                | METHOD_CALL_EXPR
                | FIELD_EXPR
                | IF_EXPR
                | LOOP_EXPR
                | WHILE_EXPR
                | RETURN_EXPR
                | BREAK_EXPR
                | BLOCK_EXPR
                | ARRAY_EXPR
                | INDEX_EXPR
                | RECORD_LIT
                | COMPTIME_EXPR
                | MATCH_EXPR
                | PERFORM_EXPR
                | SPAWN_EXPR
                | HANDLE_EXPR
                | TRY_EXPR
                | TRANSFER_EXPR
                | CHANNEL_RECV_EXPR
                | CHANNEL_SEND_EXPR
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Expr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExprKind {
    Literal(Literal),
    PrefixExpr(PrefixExpr),
    PathExpr(PathExpr),
    BinExpr(BinExpr),
    CastExpr(CastExpr),
    ParenExpr(ParenExpr),
    CallExpr(CallExpr),
    MethodCallExpr(MethodCallExpr),
    FieldExpr(FieldExpr),
    IfExpr(IfExpr),
    LoopExpr(LoopExpr),
    WhileExpr(WhileExpr),
    ReturnExpr(ReturnExpr),
    BreakExpr(BreakExpr),
    BlockExpr(BlockExpr),
    ArrayExpr(ArrayExpr),
    IndexExpr(IndexExpr),
    RecordLit(RecordLit),
    ComptimeExpr(ComptimeExpr),
    MatchExpr(MatchExpr),
    PerformExpr(PerformExpr),
    SpawnExpr(SpawnExpr),
    HandleExpr(HandleExpr),
    TryExpr(TryExpr),
    TransferExpr(TransferExpr),
    ChannelRecvExpr(ChannelRecvExpr),
    ChannelSendExpr(ChannelSendExpr),
}
impl From<Literal> for Expr {
    fn from(n: Literal) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<PrefixExpr> for Expr {
    fn from(n: PrefixExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<PathExpr> for Expr {
    fn from(n: PathExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<BinExpr> for Expr {
    fn from(n: BinExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<CastExpr> for Expr {
    fn from(n: CastExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<ParenExpr> for Expr {
    fn from(n: ParenExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<CallExpr> for Expr {
    fn from(n: CallExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<MethodCallExpr> for Expr {
    fn from(n: MethodCallExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<FieldExpr> for Expr {
    fn from(n: FieldExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<IfExpr> for Expr {
    fn from(n: IfExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<LoopExpr> for Expr {
    fn from(n: LoopExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<WhileExpr> for Expr {
    fn from(n: WhileExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<ReturnExpr> for Expr {
    fn from(n: ReturnExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<BreakExpr> for Expr {
    fn from(n: BreakExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<BlockExpr> for Expr {
    fn from(n: BlockExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<ArrayExpr> for Expr {
    fn from(n: ArrayExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<IndexExpr> for Expr {
    fn from(n: IndexExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<RecordLit> for Expr {
    fn from(n: RecordLit) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<ComptimeExpr> for Expr {
    fn from(n: ComptimeExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<MatchExpr> for Expr {
    fn from(n: MatchExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<PerformExpr> for Expr {
    fn from(n: PerformExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<SpawnExpr> for Expr {
    fn from(n: SpawnExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<HandleExpr> for Expr {
    fn from(n: HandleExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<TryExpr> for Expr {
    fn from(n: TryExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<TransferExpr> for Expr {
    fn from(n: TransferExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<ChannelRecvExpr> for Expr {
    fn from(n: ChannelRecvExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}
impl From<ChannelSendExpr> for Expr {
    fn from(n: ChannelSendExpr) -> Expr {
        Expr { syntax: n.syntax }
    }
}

impl Expr {
    pub fn kind(&self) -> ExprKind {
        match self.syntax.kind() {
            LITERAL => ExprKind::Literal(Literal::cast(self.syntax.clone()).unwrap()),
            PREFIX_EXPR => ExprKind::PrefixExpr(PrefixExpr::cast(self.syntax.clone()).unwrap()),
            PATH_EXPR => ExprKind::PathExpr(PathExpr::cast(self.syntax.clone()).unwrap()),
            BIN_EXPR => ExprKind::BinExpr(BinExpr::cast(self.syntax.clone()).unwrap()),
            CAST_EXPR => ExprKind::CastExpr(CastExpr::cast(self.syntax.clone()).unwrap()),
            PAREN_EXPR => ExprKind::ParenExpr(ParenExpr::cast(self.syntax.clone()).unwrap()),
            CALL_EXPR => ExprKind::CallExpr(CallExpr::cast(self.syntax.clone()).unwrap()),
            METHOD_CALL_EXPR => {
                ExprKind::MethodCallExpr(MethodCallExpr::cast(self.syntax.clone()).unwrap())
            }
            FIELD_EXPR => ExprKind::FieldExpr(FieldExpr::cast(self.syntax.clone()).unwrap()),
            IF_EXPR => ExprKind::IfExpr(IfExpr::cast(self.syntax.clone()).unwrap()),
            LOOP_EXPR => ExprKind::LoopExpr(LoopExpr::cast(self.syntax.clone()).unwrap()),
            WHILE_EXPR => ExprKind::WhileExpr(WhileExpr::cast(self.syntax.clone()).unwrap()),
            RETURN_EXPR => ExprKind::ReturnExpr(ReturnExpr::cast(self.syntax.clone()).unwrap()),
            BREAK_EXPR => ExprKind::BreakExpr(BreakExpr::cast(self.syntax.clone()).unwrap()),
            BLOCK_EXPR => ExprKind::BlockExpr(BlockExpr::cast(self.syntax.clone()).unwrap()),
            ARRAY_EXPR => ExprKind::ArrayExpr(ArrayExpr::cast(self.syntax.clone()).unwrap()),
            INDEX_EXPR => ExprKind::IndexExpr(IndexExpr::cast(self.syntax.clone()).unwrap()),
            RECORD_LIT => ExprKind::RecordLit(RecordLit::cast(self.syntax.clone()).unwrap()),
            COMPTIME_EXPR => {
                ExprKind::ComptimeExpr(ComptimeExpr::cast(self.syntax.clone()).unwrap())
            }
            MATCH_EXPR => ExprKind::MatchExpr(MatchExpr::cast(self.syntax.clone()).unwrap()),
            PERFORM_EXPR => ExprKind::PerformExpr(PerformExpr::cast(self.syntax.clone()).unwrap()),
            SPAWN_EXPR => ExprKind::SpawnExpr(SpawnExpr::cast(self.syntax.clone()).unwrap()),
            HANDLE_EXPR => ExprKind::HandleExpr(HandleExpr::cast(self.syntax.clone()).unwrap()),
            TRY_EXPR => ExprKind::TryExpr(TryExpr::cast(self.syntax.clone()).unwrap()),
            TRANSFER_EXPR => {
                ExprKind::TransferExpr(TransferExpr::cast(self.syntax.clone()).unwrap())
            }
            CHANNEL_RECV_EXPR => {
                ExprKind::ChannelRecvExpr(ChannelRecvExpr::cast(self.syntax.clone()).unwrap())
            }
            CHANNEL_SEND_EXPR => {
                ExprKind::ChannelSendExpr(ChannelSendExpr::cast(self.syntax.clone()).unwrap())
            }
            _ => unreachable!(),
        }
    }
}

impl Expr {}

// ExprStmt

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ExprStmt {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ExprStmt {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, EXPR_STMT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ExprStmt { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ExprStmt {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// Extend

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Extend {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Extend {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, EXTEND)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Extend { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::VisibilityOwner for Extend {}
impl ast::DocCommentsOwner for Extend {}
impl ast::AttributeOwner for Extend {}
impl Extend {
    pub fn extend_item_list(&self) -> Option<ExtendItemList> {
        super::child_opt(self)
    }

    pub fn type_ref(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }

    pub fn inheritance_list(&self) -> Option<InheritanceList> {
        super::child_opt(self)
    }
}

// ExtendItem

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ExtendItem {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ExtendItem {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, FUNCTION_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ExtendItem { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExtendItemKind {
    FunctionDef(FunctionDef),
}
impl From<FunctionDef> for ExtendItem {
    fn from(n: FunctionDef) -> ExtendItem {
        ExtendItem { syntax: n.syntax }
    }
}

impl ExtendItem {
    pub fn kind(&self) -> ExtendItemKind {
        match self.syntax.kind() {
            FUNCTION_DEF => {
                ExtendItemKind::FunctionDef(FunctionDef::cast(self.syntax.clone()).unwrap())
            }
            _ => unreachable!(),
        }
    }
}

impl ExtendItem {}

// ExtendItemList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ExtendItemList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ExtendItemList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, EXTEND_ITEM_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ExtendItemList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ExtendItemList {
    pub fn extend_items(&self) -> impl Iterator<Item = ExtendItem> {
        super::children(self)
    }
}

// ExternBlock

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ExternBlock {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ExternBlock {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, EXTERN_BLOCK)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ExternBlock { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::AttributeOwner for ExternBlock {}
impl ExternBlock {
    pub fn extern_item_list(&self) -> Option<ExternItemList> {
        super::child_opt(self)
    }
}

// ExternItem

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ExternItem {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ExternItem {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, FUNCTION_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ExternItem { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExternItemKind {
    FunctionDef(FunctionDef),
}
impl From<FunctionDef> for ExternItem {
    fn from(n: FunctionDef) -> ExternItem {
        ExternItem { syntax: n.syntax }
    }
}

impl ExternItem {
    pub fn kind(&self) -> ExternItemKind {
        match self.syntax.kind() {
            FUNCTION_DEF => {
                ExternItemKind::FunctionDef(FunctionDef::cast(self.syntax.clone()).unwrap())
            }
            _ => unreachable!(),
        }
    }
}

impl ExternItem {}

// ExternItemList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ExternItemList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ExternItemList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, EXTERN_ITEM_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ExternItemList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ExternItemList {
    pub fn extern_items(&self) -> impl Iterator<Item = ExternItem> {
        super::children(self)
    }
}

// FieldExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FieldExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for FieldExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, FIELD_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(FieldExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl FieldExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }

    pub fn name_ref(&self) -> Option<NameRef> {
        super::child_opt(self)
    }
}

// FunctionDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FunctionDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for FunctionDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, FUNCTION_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(FunctionDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for FunctionDef {}
impl ast::VisibilityOwner for FunctionDef {}
impl ast::DocCommentsOwner for FunctionDef {}
impl ast::ExternOwner for FunctionDef {}
impl ast::AttributeOwner for FunctionDef {}
impl ast::GenericParamsOwner for FunctionDef {}
impl FunctionDef {
    pub fn param_list(&self) -> Option<ParamList> {
        super::child_opt(self)
    }

    pub fn body(&self) -> Option<BlockExpr> {
        super::child_opt(self)
    }

    pub fn ret_type(&self) -> Option<RetType> {
        super::child_opt(self)
    }

    pub fn uses_clause(&self) -> Option<UsesClause> {
        super::child_opt(self)
    }
}

// GenericArgList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GenericArgList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for GenericArgList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, GENERIC_ARG_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(GenericArgList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl GenericArgList {
    pub fn generic_args(&self) -> impl Iterator<Item = TypeRef> {
        super::children(self)
    }
}

// GenericParam

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GenericParam {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for GenericParam {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, GENERIC_PARAM)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(GenericParam { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for GenericParam {}
impl GenericParam {
    pub fn bound(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }
}

// GenericParamList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct GenericParamList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for GenericParamList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, GENERIC_PARAM_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(GenericParamList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl GenericParamList {
    pub fn generic_params(&self) -> impl Iterator<Item = GenericParam> {
        super::children(self)
    }
}

// HandleExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct HandleExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for HandleExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, HANDLE_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(HandleExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl HandleExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }

    pub fn handler_arm_list(&self) -> Option<HandlerArmList> {
        super::child_opt(self)
    }
}

// HandlerArm

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct HandlerArm {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for HandlerArm {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, HANDLER_ARM)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(HandlerArm { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl HandlerArm {
    pub fn path(&self) -> Option<Path> {
        super::child_opt(self)
    }

    pub fn param_list(&self) -> Option<ParamList> {
        super::child_opt(self)
    }

    pub fn body(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// HandlerArmList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct HandlerArmList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for HandlerArmList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, HANDLER_ARM_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(HandlerArmList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl HandlerArmList {
    pub fn arms(&self) -> impl Iterator<Item = HandlerArm> {
        super::children(self)
    }
}

// IfExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct IfExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for IfExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, IF_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(IfExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl IfExpr {
    pub fn condition(&self) -> Option<Condition> {
        super::child_opt(self)
    }
}

// IndexExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct IndexExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for IndexExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, INDEX_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(IndexExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl IndexExpr {}

// InheritanceList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct InheritanceList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for InheritanceList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, INHERITANCE_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(InheritanceList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl InheritanceList {
    pub fn bounds(&self) -> impl Iterator<Item = TypeRef> {
        super::children(self)
    }
}

// LetStmt

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct LetStmt {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for LetStmt {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, LET_STMT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(LetStmt { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::TypeAscriptionOwner for LetStmt {}
impl LetStmt {
    pub fn pat(&self) -> Option<Pat> {
        super::child_opt(self)
    }

    pub fn initializer(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// Literal

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Literal {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Literal {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, LITERAL)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Literal { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Literal {}

// LiteralPat

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct LiteralPat {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for LiteralPat {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, LITERAL_PAT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(LiteralPat { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl LiteralPat {
    pub fn literal(&self) -> Option<Literal> {
        super::child_opt(self)
    }
}

// LoopExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct LoopExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for LoopExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, LOOP_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(LoopExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::LoopBodyOwner for LoopExpr {}
impl LoopExpr {}

// MacroDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MacroDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for MacroDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, MACRO_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(MacroDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for MacroDef {}
impl ast::VisibilityOwner for MacroDef {}
impl ast::DocCommentsOwner for MacroDef {}
impl ast::AttributeOwner for MacroDef {}
impl MacroDef {
    pub fn param_list(&self) -> Option<ParamList> {
        super::child_opt(self)
    }

    pub fn body(&self) -> Option<BlockExpr> {
        super::child_opt(self)
    }

    pub fn ret_type(&self) -> Option<RetType> {
        super::child_opt(self)
    }
}

// MatchArm

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MatchArm {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for MatchArm {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, MATCH_ARM)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(MatchArm { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl MatchArm {
    pub fn pat(&self) -> Option<Pat> {
        super::child_opt(self)
    }

    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// MatchArmList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MatchArmList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for MatchArmList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, MATCH_ARM_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(MatchArmList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl MatchArmList {
    pub fn arms(&self) -> impl Iterator<Item = MatchArm> {
        super::children(self)
    }
}

// MatchExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MatchExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for MatchExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, MATCH_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(MatchExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl MatchExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }

    pub fn match_arm_list(&self) -> Option<MatchArmList> {
        super::child_opt(self)
    }
}

// MethodCallExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MethodCallExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for MethodCallExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, METHOD_CALL_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(MethodCallExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::ArgListOwner for MethodCallExpr {}
impl MethodCallExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }

    pub fn name_ref(&self) -> Option<NameRef> {
        super::child_opt(self)
    }
}

// ModuleItem

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ModuleItem {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ModuleItem {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            USE | FUNCTION_DEF
                | STRUCT_DEF
                | TYPE_ALIAS_DEF
                | TRAIT_DEF
                | ENUM_DEF
                | EFFECT_DEF
                | MACRO_DEF
                | EXTEND
                | EXTERN_BLOCK
                | SUPERVISOR_DEF
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ModuleItem { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ModuleItemKind {
    Use(Use),
    FunctionDef(FunctionDef),
    StructDef(StructDef),
    TypeAliasDef(TypeAliasDef),
    TraitDef(TraitDef),
    EnumDef(EnumDef),
    EffectDef(EffectDef),
    MacroDef(MacroDef),
    Extend(Extend),
    ExternBlock(ExternBlock),
    SupervisorDef(SupervisorDef),
}
impl From<Use> for ModuleItem {
    fn from(n: Use) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<FunctionDef> for ModuleItem {
    fn from(n: FunctionDef) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<StructDef> for ModuleItem {
    fn from(n: StructDef) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<TypeAliasDef> for ModuleItem {
    fn from(n: TypeAliasDef) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<TraitDef> for ModuleItem {
    fn from(n: TraitDef) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<EnumDef> for ModuleItem {
    fn from(n: EnumDef) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<EffectDef> for ModuleItem {
    fn from(n: EffectDef) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<MacroDef> for ModuleItem {
    fn from(n: MacroDef) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<Extend> for ModuleItem {
    fn from(n: Extend) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<ExternBlock> for ModuleItem {
    fn from(n: ExternBlock) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}
impl From<SupervisorDef> for ModuleItem {
    fn from(n: SupervisorDef) -> ModuleItem {
        ModuleItem { syntax: n.syntax }
    }
}

impl ModuleItem {
    pub fn kind(&self) -> ModuleItemKind {
        match self.syntax.kind() {
            USE => ModuleItemKind::Use(Use::cast(self.syntax.clone()).unwrap()),
            FUNCTION_DEF => {
                ModuleItemKind::FunctionDef(FunctionDef::cast(self.syntax.clone()).unwrap())
            }
            STRUCT_DEF => ModuleItemKind::StructDef(StructDef::cast(self.syntax.clone()).unwrap()),
            TYPE_ALIAS_DEF => {
                ModuleItemKind::TypeAliasDef(TypeAliasDef::cast(self.syntax.clone()).unwrap())
            }
            TRAIT_DEF => ModuleItemKind::TraitDef(TraitDef::cast(self.syntax.clone()).unwrap()),
            ENUM_DEF => ModuleItemKind::EnumDef(EnumDef::cast(self.syntax.clone()).unwrap()),
            EFFECT_DEF => ModuleItemKind::EffectDef(EffectDef::cast(self.syntax.clone()).unwrap()),
            MACRO_DEF => ModuleItemKind::MacroDef(MacroDef::cast(self.syntax.clone()).unwrap()),
            EXTEND => ModuleItemKind::Extend(Extend::cast(self.syntax.clone()).unwrap()),
            EXTERN_BLOCK => {
                ModuleItemKind::ExternBlock(ExternBlock::cast(self.syntax.clone()).unwrap())
            }
            SUPERVISOR_DEF => {
                ModuleItemKind::SupervisorDef(SupervisorDef::cast(self.syntax.clone()).unwrap())
            }
            _ => unreachable!(),
        }
    }
}

impl ModuleItem {}

// Name

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Name {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Name {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, NAME)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Name { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Name {}

// NameRef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NameRef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for NameRef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, NAME_REF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(NameRef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl NameRef {}

// NeverType

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct NeverType {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for NeverType {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, NEVER_TYPE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(NeverType { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl NeverType {}

// OptionalType

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct OptionalType {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for OptionalType {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, OPTIONAL_TYPE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(OptionalType { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl OptionalType {
    pub fn type_ref(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }
}

// Param

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Param {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Param {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PARAM)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Param { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::TypeAscriptionOwner for Param {}
impl Param {
    pub fn pat(&self) -> Option<Pat> {
        super::child_opt(self)
    }
}

// ParamList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ParamList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ParamList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PARAM_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ParamList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ParamList {
    pub fn params(&self) -> impl Iterator<Item = Param> {
        super::children(self)
    }

    pub fn self_param(&self) -> Option<SelfParam> {
        super::child_opt(self)
    }
}

// ParenExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ParenExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ParenExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PAREN_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ParenExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ParenExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// Pat

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Pat {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Pat {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            BIND_PAT | PLACEHOLDER_PAT | LITERAL_PAT | PATH_PAT | TUPLE_STRUCT_PAT
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Pat { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PatKind {
    BindPat(BindPat),
    PlaceholderPat(PlaceholderPat),
    LiteralPat(LiteralPat),
    PathPat(PathPat),
    TupleStructPat(TupleStructPat),
}
impl From<BindPat> for Pat {
    fn from(n: BindPat) -> Pat {
        Pat { syntax: n.syntax }
    }
}
impl From<PlaceholderPat> for Pat {
    fn from(n: PlaceholderPat) -> Pat {
        Pat { syntax: n.syntax }
    }
}
impl From<LiteralPat> for Pat {
    fn from(n: LiteralPat) -> Pat {
        Pat { syntax: n.syntax }
    }
}
impl From<PathPat> for Pat {
    fn from(n: PathPat) -> Pat {
        Pat { syntax: n.syntax }
    }
}
impl From<TupleStructPat> for Pat {
    fn from(n: TupleStructPat) -> Pat {
        Pat { syntax: n.syntax }
    }
}

impl Pat {
    pub fn kind(&self) -> PatKind {
        match self.syntax.kind() {
            BIND_PAT => PatKind::BindPat(BindPat::cast(self.syntax.clone()).unwrap()),
            PLACEHOLDER_PAT => {
                PatKind::PlaceholderPat(PlaceholderPat::cast(self.syntax.clone()).unwrap())
            }
            LITERAL_PAT => PatKind::LiteralPat(LiteralPat::cast(self.syntax.clone()).unwrap()),
            PATH_PAT => PatKind::PathPat(PathPat::cast(self.syntax.clone()).unwrap()),
            TUPLE_STRUCT_PAT => {
                PatKind::TupleStructPat(TupleStructPat::cast(self.syntax.clone()).unwrap())
            }
            _ => unreachable!(),
        }
    }
}

impl Pat {}

// Path

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Path {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Path {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PATH)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Path { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Path {
    pub fn segment(&self) -> Option<PathSegment> {
        super::child_opt(self)
    }

    pub fn qualifier(&self) -> Option<Path> {
        super::child_opt(self)
    }
}

// PathExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PathExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for PathExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PATH_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(PathExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PathExpr {
    pub fn path(&self) -> Option<Path> {
        super::child_opt(self)
    }
}

// PathPat

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PathPat {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for PathPat {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PATH_PAT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(PathPat { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PathPat {
    pub fn path(&self) -> Option<Path> {
        super::child_opt(self)
    }
}

// PathSegment

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PathSegment {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for PathSegment {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PATH_SEGMENT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(PathSegment { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PathSegment {
    pub fn name_ref(&self) -> Option<NameRef> {
        super::child_opt(self)
    }
}

// PathType

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PathType {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for PathType {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PATH_TYPE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(PathType { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PathType {
    pub fn path(&self) -> Option<Path> {
        super::child_opt(self)
    }

    pub fn generic_arg_list(&self) -> Option<GenericArgList> {
        super::child_opt(self)
    }
}

// PerformExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PerformExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for PerformExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PERFORM_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(PerformExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::ArgListOwner for PerformExpr {}
impl PerformExpr {
    pub fn path(&self) -> Option<Path> {
        super::child_opt(self)
    }
}

// PlaceholderPat

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PlaceholderPat {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for PlaceholderPat {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PLACEHOLDER_PAT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(PlaceholderPat { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PlaceholderPat {}

// PrefixExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct PrefixExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for PrefixExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, PREFIX_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(PrefixExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl PrefixExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// RecordField

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RecordField {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for RecordField {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, RECORD_FIELD)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(RecordField { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl RecordField {
    pub fn name_ref(&self) -> Option<NameRef> {
        super::child_opt(self)
    }

    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// RecordFieldDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RecordFieldDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for RecordFieldDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, RECORD_FIELD_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(RecordFieldDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for RecordFieldDef {}
impl ast::VisibilityOwner for RecordFieldDef {}
impl ast::DocCommentsOwner for RecordFieldDef {}
impl ast::TypeAscriptionOwner for RecordFieldDef {}
impl RecordFieldDef {}

// RecordFieldDefList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RecordFieldDefList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for RecordFieldDefList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, RECORD_FIELD_DEF_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(RecordFieldDefList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl RecordFieldDefList {
    pub fn fields(&self) -> impl Iterator<Item = RecordFieldDef> {
        super::children(self)
    }
}

// RecordFieldList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RecordFieldList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for RecordFieldList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, RECORD_FIELD_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(RecordFieldList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl RecordFieldList {
    pub fn fields(&self) -> impl Iterator<Item = RecordField> {
        super::children(self)
    }

    pub fn spread(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// RecordLit

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RecordLit {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for RecordLit {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, RECORD_LIT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(RecordLit { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl RecordLit {
    pub fn type_ref(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }

    pub fn record_field_list(&self) -> Option<RecordFieldList> {
        super::child_opt(self)
    }
}

// RefinementType

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RefinementType {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for RefinementType {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, REFINEMENT_TYPE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(RefinementType { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl RefinementType {
    pub fn base(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }

    pub fn binder(&self) -> Option<NameRef> {
        super::child_opt(self)
    }

    pub fn predicate(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// Rename

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Rename {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Rename {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, RENAME)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Rename { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for Rename {}
impl Rename {}

// RetType

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct RetType {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for RetType {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, RET_TYPE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(RetType { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl RetType {
    pub fn type_ref(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }
}

// ReturnExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct ReturnExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for ReturnExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, RETURN_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(ReturnExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ReturnExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// SelfParam

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SelfParam {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for SelfParam {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, SELF_PARAM)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(SelfParam { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::TypeAscriptionOwner for SelfParam {}
impl SelfParam {}

// SourceFile

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SourceFile {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for SourceFile {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, SOURCE_FILE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(SourceFile { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::ModuleItemOwner for SourceFile {}
impl ast::FunctionDefOwner for SourceFile {}
impl SourceFile {}

// SpawnExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SpawnExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for SpawnExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, SPAWN_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(SpawnExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SpawnExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// Stmt

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Stmt {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Stmt {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, LET_STMT | EXPR_STMT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Stmt { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StmtKind {
    LetStmt(LetStmt),
    ExprStmt(ExprStmt),
}
impl From<LetStmt> for Stmt {
    fn from(n: LetStmt) -> Stmt {
        Stmt { syntax: n.syntax }
    }
}
impl From<ExprStmt> for Stmt {
    fn from(n: ExprStmt) -> Stmt {
        Stmt { syntax: n.syntax }
    }
}

impl Stmt {
    pub fn kind(&self) -> StmtKind {
        match self.syntax.kind() {
            LET_STMT => StmtKind::LetStmt(LetStmt::cast(self.syntax.clone()).unwrap()),
            EXPR_STMT => StmtKind::ExprStmt(ExprStmt::cast(self.syntax.clone()).unwrap()),
            _ => unreachable!(),
        }
    }
}

impl Stmt {}

// StructDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct StructDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for StructDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, STRUCT_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(StructDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for StructDef {}
impl ast::VisibilityOwner for StructDef {}
impl ast::DocCommentsOwner for StructDef {}
impl ast::AttributeOwner for StructDef {}
impl ast::GenericParamsOwner for StructDef {}
impl StructDef {
    pub fn inheritance_list(&self) -> Option<InheritanceList> {
        super::child_opt(self)
    }

    pub fn where_clause(&self) -> Option<WhereClause> {
        super::child_opt(self)
    }
}

// SupervisorDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SupervisorDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for SupervisorDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, SUPERVISOR_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(SupervisorDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for SupervisorDef {}
impl ast::VisibilityOwner for SupervisorDef {}
impl ast::DocCommentsOwner for SupervisorDef {}
impl ast::AttributeOwner for SupervisorDef {}
impl SupervisorDef {
    pub fn supervisor_item_list(&self) -> Option<SupervisorItemList> {
        super::child_opt(self)
    }
}

// SupervisorEntry

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SupervisorEntry {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for SupervisorEntry {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, SUPERVISOR_ENTRY)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(SupervisorEntry { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for SupervisorEntry {}
impl SupervisorEntry {
    pub fn value(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// SupervisorItem

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SupervisorItem {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for SupervisorItem {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, SUPERVISOR_ENTRY | CHILD_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(SupervisorItem { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SupervisorItemKind {
    SupervisorEntry(SupervisorEntry),
    ChildDef(ChildDef),
}
impl From<SupervisorEntry> for SupervisorItem {
    fn from(n: SupervisorEntry) -> SupervisorItem {
        SupervisorItem { syntax: n.syntax }
    }
}
impl From<ChildDef> for SupervisorItem {
    fn from(n: ChildDef) -> SupervisorItem {
        SupervisorItem { syntax: n.syntax }
    }
}

impl SupervisorItem {
    pub fn kind(&self) -> SupervisorItemKind {
        match self.syntax.kind() {
            SUPERVISOR_ENTRY => SupervisorItemKind::SupervisorEntry(
                SupervisorEntry::cast(self.syntax.clone()).unwrap(),
            ),
            CHILD_DEF => SupervisorItemKind::ChildDef(ChildDef::cast(self.syntax.clone()).unwrap()),
            _ => unreachable!(),
        }
    }
}

impl SupervisorItem {}

// SupervisorItemList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct SupervisorItemList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for SupervisorItemList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, SUPERVISOR_ITEM_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(SupervisorItemList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl SupervisorItemList {
    pub fn items(&self) -> impl Iterator<Item = SupervisorItem> {
        super::children(self)
    }
}

// TraitDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TraitDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for TraitDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, TRAIT_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(TraitDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for TraitDef {}
impl ast::VisibilityOwner for TraitDef {}
impl ast::DocCommentsOwner for TraitDef {}
impl ast::AttributeOwner for TraitDef {}
impl ast::GenericParamsOwner for TraitDef {}
impl TraitDef {
    pub fn inheritance_list(&self) -> Option<InheritanceList> {
        super::child_opt(self)
    }

    pub fn extend_item_list(&self) -> Option<ExtendItemList> {
        super::child_opt(self)
    }
}

// TransferExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TransferExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for TransferExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, TRANSFER_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(TransferExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl TransferExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// TryExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TryExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for TryExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, TRY_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(TryExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl TryExpr {
    pub fn expr(&self) -> Option<Expr> {
        super::child_opt(self)
    }
}

// TupleFieldDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TupleFieldDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for TupleFieldDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, TUPLE_FIELD_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(TupleFieldDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::VisibilityOwner for TupleFieldDef {}
impl TupleFieldDef {
    pub fn type_ref(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }
}

// TupleFieldDefList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TupleFieldDefList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for TupleFieldDefList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, TUPLE_FIELD_DEF_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(TupleFieldDefList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl TupleFieldDefList {
    pub fn fields(&self) -> impl Iterator<Item = TupleFieldDef> {
        super::children(self)
    }
}

// TupleStructPat

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TupleStructPat {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for TupleStructPat {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, TUPLE_STRUCT_PAT)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(TupleStructPat { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl TupleStructPat {
    pub fn args(&self) -> impl Iterator<Item = Pat> {
        super::children(self)
    }

    pub fn path(&self) -> Option<Path> {
        super::child_opt(self)
    }
}

// TypeAliasDef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TypeAliasDef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for TypeAliasDef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, TYPE_ALIAS_DEF)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(TypeAliasDef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::NameOwner for TypeAliasDef {}
impl ast::VisibilityOwner for TypeAliasDef {}
impl ast::DocCommentsOwner for TypeAliasDef {}
impl ast::AttributeOwner for TypeAliasDef {}
impl TypeAliasDef {
    pub fn type_ref(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }
}

// TypeRef

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct TypeRef {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for TypeRef {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(
            kind,
            PATH_TYPE | ARRAY_TYPE | NEVER_TYPE | OPTIONAL_TYPE | REFINEMENT_TYPE
        )
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(TypeRef { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TypeRefKind {
    PathType(PathType),
    ArrayType(ArrayType),
    NeverType(NeverType),
    OptionalType(OptionalType),
    RefinementType(RefinementType),
}
impl From<PathType> for TypeRef {
    fn from(n: PathType) -> TypeRef {
        TypeRef { syntax: n.syntax }
    }
}
impl From<ArrayType> for TypeRef {
    fn from(n: ArrayType) -> TypeRef {
        TypeRef { syntax: n.syntax }
    }
}
impl From<NeverType> for TypeRef {
    fn from(n: NeverType) -> TypeRef {
        TypeRef { syntax: n.syntax }
    }
}
impl From<OptionalType> for TypeRef {
    fn from(n: OptionalType) -> TypeRef {
        TypeRef { syntax: n.syntax }
    }
}
impl From<RefinementType> for TypeRef {
    fn from(n: RefinementType) -> TypeRef {
        TypeRef { syntax: n.syntax }
    }
}

impl TypeRef {
    pub fn kind(&self) -> TypeRefKind {
        match self.syntax.kind() {
            PATH_TYPE => TypeRefKind::PathType(PathType::cast(self.syntax.clone()).unwrap()),
            ARRAY_TYPE => TypeRefKind::ArrayType(ArrayType::cast(self.syntax.clone()).unwrap()),
            NEVER_TYPE => TypeRefKind::NeverType(NeverType::cast(self.syntax.clone()).unwrap()),
            OPTIONAL_TYPE => {
                TypeRefKind::OptionalType(OptionalType::cast(self.syntax.clone()).unwrap())
            }
            REFINEMENT_TYPE => {
                TypeRefKind::RefinementType(RefinementType::cast(self.syntax.clone()).unwrap())
            }
            _ => unreachable!(),
        }
    }
}

impl TypeRef {}

// Use

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Use {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Use {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, USE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Use { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::VisibilityOwner for Use {}
impl Use {
    pub fn use_tree(&self) -> Option<UseTree> {
        super::child_opt(self)
    }
}

// UseTree

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UseTree {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for UseTree {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, USE_TREE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(UseTree { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl UseTree {
    pub fn use_tree_list(&self) -> Option<UseTreeList> {
        super::child_opt(self)
    }

    pub fn path(&self) -> Option<Path> {
        super::child_opt(self)
    }

    pub fn rename(&self) -> Option<Rename> {
        super::child_opt(self)
    }
}

// UseTreeList

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UseTreeList {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for UseTreeList {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, USE_TREE_LIST)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(UseTreeList { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl UseTreeList {
    pub fn use_trees(&self) -> impl Iterator<Item = UseTree> {
        super::children(self)
    }
}

// UsesClause

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct UsesClause {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for UsesClause {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, USES_CLAUSE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(UsesClause { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl UsesClause {
    pub fn effects(&self) -> impl Iterator<Item = Path> {
        super::children(self)
    }
}

// Visibility

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct Visibility {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for Visibility {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, VISIBILITY)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Visibility { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl Visibility {}

// WhereClause

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WhereClause {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for WhereClause {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, WHERE_CLAUSE)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(WhereClause { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl WhereClause {
    pub fn predicates(&self) -> impl Iterator<Item = WherePred> {
        super::children(self)
    }
}

// WherePred

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WherePred {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for WherePred {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, WHERE_PRED)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(WherePred { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl WherePred {
    pub fn type_ref(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }

    pub fn bound(&self) -> Option<TypeRef> {
        super::child_opt(self)
    }
}

// WhileExpr

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct WhileExpr {
    pub(crate) syntax: SyntaxNode,
}

impl AstNode for WhileExpr {
    fn can_cast(kind: SyntaxKind) -> bool {
        matches!(kind, WHILE_EXPR)
    }
    fn cast(syntax: SyntaxNode) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(WhileExpr { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxNode {
        &self.syntax
    }
}
impl ast::LoopBodyOwner for WhileExpr {}
impl WhileExpr {
    pub fn condition(&self) -> Option<Condition> {
        super::child_opt(self)
    }
}

// IntNumber

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct IntNumber {
    pub(crate) syntax: SyntaxToken,
}
impl std::fmt::Display for IntNumber {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.syntax, f)
    }
}
impl AstToken for IntNumber {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == INT_NUMBER
    }
    fn cast(syntax: SyntaxToken) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxToken {
        &self.syntax
    }
}

// FloatNumber

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct FloatNumber {
    pub(crate) syntax: SyntaxToken,
}
impl std::fmt::Display for FloatNumber {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.syntax, f)
    }
}
impl AstToken for FloatNumber {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == FLOAT_NUMBER
    }
    fn cast(syntax: SyntaxToken) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxToken {
        &self.syntax
    }
}

// String

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct String {
    pub(crate) syntax: SyntaxToken,
}
impl std::fmt::Display for String {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        std::fmt::Display::fmt(&self.syntax, f)
    }
}
impl AstToken for String {
    fn can_cast(kind: SyntaxKind) -> bool {
        kind == STRING
    }
    fn cast(syntax: SyntaxToken) -> Option<Self> {
        if Self::can_cast(syntax.kind()) {
            Some(Self { syntax })
        } else {
            None
        }
    }
    fn syntax(&self) -> &SyntaxToken {
        &self.syntax
    }
}
