//! Generated file, do not edit by hand, see `crate/ra_tools/src/codegen`

// This file is automatically generated based on the file `./generated.rs.tera`
// when `cargo gen-syntax` is run Do not edit manually

#![allow(
    bad_style,
    missing_docs,
    unreachable_pub,
    clippy::enum_glob_use,
    clippy::manual_non_exhaustive,
    clippy::upper_case_acronyms
)]
use super::SyntaxInfo;

/// The kind of syntax node, e.g. `IDENT`, `USE_KW`, or `STRUCT_DEF`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[repr(u16)]
#[non_exhaustive]
pub enum SyntaxKind {
    // Technical SyntaxKinds: they appear temporally during parsing,
    // but never end up in the final tree
    #[doc(hidden)]
    TOMBSTONE,
    #[doc(hidden)]
    EOF,
    AMP,
    PIPE,
    PLUS,
    MINUS,
    STAR,
    SLASH,
    PERCENT,
    CARET,
    HASH,
    DOT,
    LT,
    GT,
    EQ,
    L_PAREN,
    R_PAREN,
    L_CURLY,
    R_CURLY,
    L_BRACKET,
    R_BRACKET,
    SEMI,
    COLON,
    COMMA,
    EXCLAMATION,
    QUESTION,
    AT,
    TILDE,
    UNDERSCORE,
    EQEQ,
    NEQ,
    LTEQ,
    GTEQ,
    DOTDOT,
    DOTDOTDOT,
    PLUSEQ,
    MINUSEQ,
    STAREQ,
    SLASHEQ,
    PERCENTEQ,
    SHLEQ,
    SHREQ,
    AMPEQ,
    PIPEEQ,
    CARETEQ,
    DOTDOTEQ,
    THIN_ARROW,
    LARROW,
    AMPAMP,
    PIPEPIPE,
    SHL,
    SHR,
    BREAK_KW,
    DO_KW,
    ELSE_KW,
    FALSE_KW,
    FOR_KW,
    FUNC_KW,
    IF_KW,
    IN_KW,
    AS_KW,
    IMPORT_KW,
    NIL_KW,
    RETURN_KW,
    TRUE_KW,
    WHILE_KW,
    LOOP_KW,
    LET_KW,
    VAR_KW,
    STATIC_KW,
    INIT_KW,
    OVERRIDE_KW,
    CLASS_KW,
    STRUCT_KW,
    TRAIT_KW,
    EXTEND_KW,
    ENUM_KW,
    NEVER_KW,
    TYPE_KW,
    WHERE_KW,
    PUBLIC_KW,
    INTERNAL_KW,
    ROOT_KW,
    SUPER_KW,
    SELF_KW,
    MATCH_KW,
    COMPTIME_KW,
    MACRO_KW,
    EFFECT_KW,
    USES_KW,
    PERFORM_KW,
    HANDLE_KW,
    RESUME_KW,
    EXTERN_KW,
    SUPERVISOR_KW,
    CHILD_KW,
    SPAWN_KW,
    CONSUMING_KW,
    BORROWING_KW,
    INOUT_KW,
    READ_KW,
    OUT_KW,
    MUT_KW,
    DEF_KW,
    DATA_KW,
    INT_NUMBER,
    FLOAT_NUMBER,
    STRING,
    ERROR,
    IDENT,
    INDEX,
    WHITESPACE,
    COMMENT,
    SOURCE_FILE,
    ATTRIBUTE_LIST,
    ATTRIBUTE,
    FUNCTION_DEF,
    EXTERN,
    RET_TYPE,
    VISIBILITY,
    USES_CLAUSE,
    PARAM_LIST,
    PARAM,
    SELF_PARAM,
    GENERIC_PARAM_LIST,
    GENERIC_PARAM,
    GENERIC_ARG_LIST,
    WHERE_CLAUSE,
    WHERE_PRED,
    INHERITANCE_LIST,
    STRUCT_DEF,
    TYPE_ALIAS_DEF,
    CONST_DEF,
    RECORD_FIELD_DEF_LIST,
    RECORD_FIELD_DEF,
    TUPLE_FIELD_DEF_LIST,
    TUPLE_FIELD_DEF,
    TRAIT_DEF,
    ENUM_DEF,
    ENUM_VARIANT_LIST,
    ENUM_VARIANT,
    EFFECT_DEF,
    EFFECT_OP_LIST,
    EFFECT_OP,
    MACRO_DEF,
    PATH_TYPE,
    ARRAY_TYPE,
    TUPLE_TYPE,
    PAREN_TYPE,
    REFERENCE_TYPE,
    FUNCTION_TYPE,
    VARIADIC_TYPE,
    NEVER_TYPE,
    OPTIONAL_TYPE,
    REFINEMENT_TYPE,
    SUPERVISOR_DEF,
    SUPERVISOR_ITEM_LIST,
    SUPERVISOR_ENTRY,
    CHILD_DEF,
    LET_STMT,
    EXPR_STMT,
    PATH_EXPR,
    PREFIX_EXPR,
    LITERAL,
    BIN_EXPR,
    CAST_EXPR,
    PAREN_EXPR,
    CALL_EXPR,
    METHOD_CALL_EXPR,
    FIELD_EXPR,
    IF_EXPR,
    INDEX_EXPR,
    BLOCK_EXPR,
    RETURN_EXPR,
    WHILE_EXPR,
    LOOP_EXPR,
    BREAK_EXPR,
    ARRAY_EXPR,
    TUPLE_EXPR,
    CLOSURE_EXPR,
    CONDITION,
    COMPTIME_EXPR,
    MATCH_EXPR,
    MATCH_ARM_LIST,
    MATCH_ARM,
    PERFORM_EXPR,
    SPAWN_EXPR,
    HANDLE_EXPR,
    HANDLER_ARM_LIST,
    HANDLER_ARM,
    TRY_EXPR,
    TRANSFER_EXPR,
    CHANNEL_RECV_EXPR,
    CHANNEL_SEND_EXPR,
    BIND_PAT,
    PLACEHOLDER_PAT,
    LITERAL_PAT,
    PATH_PAT,
    TUPLE_STRUCT_PAT,
    TUPLE_PAT,
    PAREN_PAT,
    ARG_LIST,
    NAME,
    NAME_REF,
    PATH,
    PATH_SEGMENT,
    RECORD_LIT,
    RECORD_FIELD_LIST,
    RECORD_FIELD,
    USE,
    USE_TREE,
    USE_TREE_LIST,
    RENAME,
    EXTEND,
    EXTEND_ITEM_LIST,
    EXTEND_ITEM,
    EXTERN_BLOCK,
    EXTERN_ITEM_LIST,
    EXTERN_ITEM,
    // Technical kind so that we can cast from u16 safely
    #[doc(hidden)]
    __LAST,
}
use self::SyntaxKind::*;

#[macro_export]
macro_rules! T {
    (&) => {
        $crate::SyntaxKind::AMP
    };
    (|) => {
        $crate::SyntaxKind::PIPE
    };
    (+) => {
        $crate::SyntaxKind::PLUS
    };
    (-) => {
        $crate::SyntaxKind::MINUS
    };
    (*) => {
        $crate::SyntaxKind::STAR
    };
    (/) => {
        $crate::SyntaxKind::SLASH
    };
    (%) => {
        $crate::SyntaxKind::PERCENT
    };
    (^) => {
        $crate::SyntaxKind::CARET
    };
    (#) => {
        $crate::SyntaxKind::HASH
    };
    (.) => {
        $crate::SyntaxKind::DOT
    };
    (<) => {
        $crate::SyntaxKind::LT
    };
    (>) => {
        $crate::SyntaxKind::GT
    };
    (=) => {
        $crate::SyntaxKind::EQ
    };
    ('(') => {
        $crate::SyntaxKind::L_PAREN
    };
    (')') => {
        $crate::SyntaxKind::R_PAREN
    };
    ('{') => {
        $crate::SyntaxKind::L_CURLY
    };
    ('}') => {
        $crate::SyntaxKind::R_CURLY
    };
    ('[') => {
        $crate::SyntaxKind::L_BRACKET
    };
    (']') => {
        $crate::SyntaxKind::R_BRACKET
    };
    (;) => {
        $crate::SyntaxKind::SEMI
    };
    (:) => {
        $crate::SyntaxKind::COLON
    };
    (,) => {
        $crate::SyntaxKind::COMMA
    };
    (!) => {
        $crate::SyntaxKind::EXCLAMATION
    };
    (?) => {
        $crate::SyntaxKind::QUESTION
    };
    (@) => {
        $crate::SyntaxKind::AT
    };
    (~) => {
        $crate::SyntaxKind::TILDE
    };
    (_) => {
        $crate::SyntaxKind::UNDERSCORE
    };
    (==) => {
        $crate::SyntaxKind::EQEQ
    };
    (!=) => {
        $crate::SyntaxKind::NEQ
    };
    (<=) => {
        $crate::SyntaxKind::LTEQ
    };
    (>=) => {
        $crate::SyntaxKind::GTEQ
    };
    (..) => {
        $crate::SyntaxKind::DOTDOT
    };
    (...) => {
        $crate::SyntaxKind::DOTDOTDOT
    };
    (+=) => {
        $crate::SyntaxKind::PLUSEQ
    };
    (-=) => {
        $crate::SyntaxKind::MINUSEQ
    };
    (*=) => {
        $crate::SyntaxKind::STAREQ
    };
    (/=) => {
        $crate::SyntaxKind::SLASHEQ
    };
    (%=) => {
        $crate::SyntaxKind::PERCENTEQ
    };
    (<<=) => {
        $crate::SyntaxKind::SHLEQ
    };
    (>>=) => {
        $crate::SyntaxKind::SHREQ
    };
    (&=) => {
        $crate::SyntaxKind::AMPEQ
    };
    (|=) => {
        $crate::SyntaxKind::PIPEEQ
    };
    (^=) => {
        $crate::SyntaxKind::CARETEQ
    };
    (..=) => {
        $crate::SyntaxKind::DOTDOTEQ
    };
    (->) => {
        $crate::SyntaxKind::THIN_ARROW
    };
    (<-) => {
        $crate::SyntaxKind::LARROW
    };
    (&&) => {
        $crate::SyntaxKind::AMPAMP
    };
    (||) => {
        $crate::SyntaxKind::PIPEPIPE
    };
    (<<) => {
        $crate::SyntaxKind::SHL
    };
    (>>) => {
        $crate::SyntaxKind::SHR
    };
    (break) => {
        $crate::SyntaxKind::BREAK_KW
    };
    (do) => {
        $crate::SyntaxKind::DO_KW
    };
    (else) => {
        $crate::SyntaxKind::ELSE_KW
    };
    (false) => {
        $crate::SyntaxKind::FALSE_KW
    };
    (for) => {
        $crate::SyntaxKind::FOR_KW
    };
    (func) => {
        $crate::SyntaxKind::FUNC_KW
    };
    (if) => {
        $crate::SyntaxKind::IF_KW
    };
    (in) => {
        $crate::SyntaxKind::IN_KW
    };
    (as) => {
        $crate::SyntaxKind::AS_KW
    };
    (import) => {
        $crate::SyntaxKind::IMPORT_KW
    };
    (nil) => {
        $crate::SyntaxKind::NIL_KW
    };
    (return) => {
        $crate::SyntaxKind::RETURN_KW
    };
    (true) => {
        $crate::SyntaxKind::TRUE_KW
    };
    (while) => {
        $crate::SyntaxKind::WHILE_KW
    };
    (loop) => {
        $crate::SyntaxKind::LOOP_KW
    };
    (let) => {
        $crate::SyntaxKind::LET_KW
    };
    (var) => {
        $crate::SyntaxKind::VAR_KW
    };
    (static) => {
        $crate::SyntaxKind::STATIC_KW
    };
    (init) => {
        $crate::SyntaxKind::INIT_KW
    };
    (override) => {
        $crate::SyntaxKind::OVERRIDE_KW
    };
    (class) => {
        $crate::SyntaxKind::CLASS_KW
    };
    (struct) => {
        $crate::SyntaxKind::STRUCT_KW
    };
    (trait) => {
        $crate::SyntaxKind::TRAIT_KW
    };
    (extend) => {
        $crate::SyntaxKind::EXTEND_KW
    };
    (enum) => {
        $crate::SyntaxKind::ENUM_KW
    };
    (never) => {
        $crate::SyntaxKind::NEVER_KW
    };
    (type) => {
        $crate::SyntaxKind::TYPE_KW
    };
    (where) => {
        $crate::SyntaxKind::WHERE_KW
    };
    (public) => {
        $crate::SyntaxKind::PUBLIC_KW
    };
    (internal) => {
        $crate::SyntaxKind::INTERNAL_KW
    };
    (root) => {
        $crate::SyntaxKind::ROOT_KW
    };
    (super) => {
        $crate::SyntaxKind::SUPER_KW
    };
    (self) => {
        $crate::SyntaxKind::SELF_KW
    };
    (match) => {
        $crate::SyntaxKind::MATCH_KW
    };
    (comptime) => {
        $crate::SyntaxKind::COMPTIME_KW
    };
    (macro) => {
        $crate::SyntaxKind::MACRO_KW
    };
    (effect) => {
        $crate::SyntaxKind::EFFECT_KW
    };
    (uses) => {
        $crate::SyntaxKind::USES_KW
    };
    (perform) => {
        $crate::SyntaxKind::PERFORM_KW
    };
    (handle) => {
        $crate::SyntaxKind::HANDLE_KW
    };
    (resume) => {
        $crate::SyntaxKind::RESUME_KW
    };
    (extern) => {
        $crate::SyntaxKind::EXTERN_KW
    };
    (supervisor) => {
        $crate::SyntaxKind::SUPERVISOR_KW
    };
    (child) => {
        $crate::SyntaxKind::CHILD_KW
    };
    (spawn) => {
        $crate::SyntaxKind::SPAWN_KW
    };
    (consuming) => {
        $crate::SyntaxKind::CONSUMING_KW
    };
    (borrowing) => {
        $crate::SyntaxKind::BORROWING_KW
    };
    (inout) => {
        $crate::SyntaxKind::INOUT_KW
    };
    (read) => {
        $crate::SyntaxKind::READ_KW
    };
    (out) => {
        $crate::SyntaxKind::OUT_KW
    };
    (mut) => {
        $crate::SyntaxKind::MUT_KW
    };
    (def) => {
        $crate::SyntaxKind::DEF_KW
    };
    (data) => {
        $crate::SyntaxKind::DATA_KW
    };
}

impl From<u16> for SyntaxKind {
    fn from(d: u16) -> SyntaxKind {
        assert!(d <= (__LAST as u16));
        unsafe { std::mem::transmute::<u16, SyntaxKind>(d) }
    }
}

impl From<SyntaxKind> for u16 {
    fn from(k: SyntaxKind) -> u16 {
        k as u16
    }
}

impl SyntaxKind {
    #[rustfmt::skip]
    pub fn is_keyword(self) -> bool {
        matches!(self,
        BREAK_KW
        | DO_KW
        | ELSE_KW
        | FALSE_KW
        | FOR_KW
        | FUNC_KW
        | IF_KW
        | IN_KW
        | AS_KW
        | IMPORT_KW
        | NIL_KW
        | RETURN_KW
        | TRUE_KW
        | WHILE_KW
        | LOOP_KW
        | LET_KW
        | VAR_KW
        | STATIC_KW
        | INIT_KW
        | OVERRIDE_KW
        | CLASS_KW
        | STRUCT_KW
        | TRAIT_KW
        | EXTEND_KW
        | ENUM_KW
        | NEVER_KW
        | TYPE_KW
        | WHERE_KW
        | PUBLIC_KW
        | INTERNAL_KW
        | ROOT_KW
        | SUPER_KW
        | SELF_KW
        | MATCH_KW
        | COMPTIME_KW
        | MACRO_KW
        | EFFECT_KW
        | USES_KW
        | PERFORM_KW
        | HANDLE_KW
        | RESUME_KW
        | EXTERN_KW
        | SUPERVISOR_KW
        | CHILD_KW
        | SPAWN_KW
        | CONSUMING_KW
        | BORROWING_KW
        | INOUT_KW
        | READ_KW
        | OUT_KW
        | MUT_KW
        | DEF_KW
        | DATA_KW
        )
    }

    #[rustfmt::skip]
    pub fn is_symbol(self) -> bool {
        matches!(self,
        AMP
        | PIPE
        | PLUS
        | MINUS
        | STAR
        | SLASH
        | PERCENT
        | CARET
        | HASH
        | DOT
        | LT
        | GT
        | EQ
        | L_PAREN
        | R_PAREN
        | L_CURLY
        | R_CURLY
        | L_BRACKET
        | R_BRACKET
        | SEMI
        | COLON
        | COMMA
        | EXCLAMATION
        | QUESTION
        | AT
        | TILDE
        | UNDERSCORE
        | EQEQ
        | NEQ
        | LTEQ
        | GTEQ
        | DOTDOT
        | DOTDOTDOT
        | PLUSEQ
        | MINUSEQ
        | STAREQ
        | SLASHEQ
        | PERCENTEQ
        | SHLEQ
        | SHREQ
        | AMPEQ
        | PIPEEQ
        | CARETEQ
        | DOTDOTEQ
        | THIN_ARROW
        | LARROW
        | AMPAMP
        | PIPEPIPE
        | SHL
        | SHR
        )
    }

    #[rustfmt::skip]
    pub fn is_literal(self) -> bool {
        matches!(self,
            INT_NUMBER
            | FLOAT_NUMBER
            | STRING
        )
    }

    #[rustfmt::skip]
    pub(crate) fn info(self) -> &'static SyntaxInfo {
        match self {
            AMP => &SyntaxInfo { name: "AMP" },
            PIPE => &SyntaxInfo { name: "PIPE" },
            PLUS => &SyntaxInfo { name: "PLUS" },
            MINUS => &SyntaxInfo { name: "MINUS" },
            STAR => &SyntaxInfo { name: "STAR" },
            SLASH => &SyntaxInfo { name: "SLASH" },
            PERCENT => &SyntaxInfo { name: "PERCENT" },
            CARET => &SyntaxInfo { name: "CARET" },
            HASH => &SyntaxInfo { name: "HASH" },
            DOT => &SyntaxInfo { name: "DOT" },
            LT => &SyntaxInfo { name: "LT" },
            GT => &SyntaxInfo { name: "GT" },
            EQ => &SyntaxInfo { name: "EQ" },
            L_PAREN => &SyntaxInfo { name: "L_PAREN" },
            R_PAREN => &SyntaxInfo { name: "R_PAREN" },
            L_CURLY => &SyntaxInfo { name: "L_CURLY" },
            R_CURLY => &SyntaxInfo { name: "R_CURLY" },
            L_BRACKET => &SyntaxInfo { name: "L_BRACKET" },
            R_BRACKET => &SyntaxInfo { name: "R_BRACKET" },
            SEMI => &SyntaxInfo { name: "SEMI" },
            COLON => &SyntaxInfo { name: "COLON" },
            COMMA => &SyntaxInfo { name: "COMMA" },
            EXCLAMATION => &SyntaxInfo { name: "EXCLAMATION" },
            QUESTION => &SyntaxInfo { name: "QUESTION" },
            AT => &SyntaxInfo { name: "AT" },
            TILDE => &SyntaxInfo { name: "TILDE" },
            UNDERSCORE => &SyntaxInfo { name: "UNDERSCORE" },
            EQEQ => &SyntaxInfo { name: "EQEQ" },
            NEQ => &SyntaxInfo { name: "NEQ" },
            LTEQ => &SyntaxInfo { name: "LTEQ" },
            GTEQ => &SyntaxInfo { name: "GTEQ" },
            DOTDOT => &SyntaxInfo { name: "DOTDOT" },
            DOTDOTDOT => &SyntaxInfo { name: "DOTDOTDOT" },
            PLUSEQ => &SyntaxInfo { name: "PLUSEQ" },
            MINUSEQ => &SyntaxInfo { name: "MINUSEQ" },
            STAREQ => &SyntaxInfo { name: "STAREQ" },
            SLASHEQ => &SyntaxInfo { name: "SLASHEQ" },
            PERCENTEQ => &SyntaxInfo { name: "PERCENTEQ" },
            SHLEQ => &SyntaxInfo { name: "SHLEQ" },
            SHREQ => &SyntaxInfo { name: "SHREQ" },
            AMPEQ => &SyntaxInfo { name: "AMPEQ" },
            PIPEEQ => &SyntaxInfo { name: "PIPEEQ" },
            CARETEQ => &SyntaxInfo { name: "CARETEQ" },
            DOTDOTEQ => &SyntaxInfo { name: "DOTDOTEQ" },
            THIN_ARROW => &SyntaxInfo { name: "THIN_ARROW" },
            LARROW => &SyntaxInfo { name: "LARROW" },
            AMPAMP => &SyntaxInfo { name: "AMPAMP" },
            PIPEPIPE => &SyntaxInfo { name: "PIPEPIPE" },
            SHL => &SyntaxInfo { name: "SHL" },
            SHR => &SyntaxInfo { name: "SHR" },
            BREAK_KW => &SyntaxInfo { name: "BREAK_KW" },
            DO_KW => &SyntaxInfo { name: "DO_KW" },
            ELSE_KW => &SyntaxInfo { name: "ELSE_KW" },
            FALSE_KW => &SyntaxInfo { name: "FALSE_KW" },
            FOR_KW => &SyntaxInfo { name: "FOR_KW" },
            FUNC_KW => &SyntaxInfo { name: "FUNC_KW" },
            IF_KW => &SyntaxInfo { name: "IF_KW" },
            IN_KW => &SyntaxInfo { name: "IN_KW" },
            AS_KW => &SyntaxInfo { name: "AS_KW" },
            IMPORT_KW => &SyntaxInfo { name: "IMPORT_KW" },
            NIL_KW => &SyntaxInfo { name: "NIL_KW" },
            RETURN_KW => &SyntaxInfo { name: "RETURN_KW" },
            TRUE_KW => &SyntaxInfo { name: "TRUE_KW" },
            WHILE_KW => &SyntaxInfo { name: "WHILE_KW" },
            LOOP_KW => &SyntaxInfo { name: "LOOP_KW" },
            LET_KW => &SyntaxInfo { name: "LET_KW" },
            VAR_KW => &SyntaxInfo { name: "VAR_KW" },
            STATIC_KW => &SyntaxInfo { name: "STATIC_KW" },
            INIT_KW => &SyntaxInfo { name: "INIT_KW" },
            OVERRIDE_KW => &SyntaxInfo { name: "OVERRIDE_KW" },
            CLASS_KW => &SyntaxInfo { name: "CLASS_KW" },
            STRUCT_KW => &SyntaxInfo { name: "STRUCT_KW" },
            TRAIT_KW => &SyntaxInfo { name: "TRAIT_KW" },
            EXTEND_KW => &SyntaxInfo { name: "EXTEND_KW" },
            ENUM_KW => &SyntaxInfo { name: "ENUM_KW" },
            NEVER_KW => &SyntaxInfo { name: "NEVER_KW" },
            TYPE_KW => &SyntaxInfo { name: "TYPE_KW" },
            WHERE_KW => &SyntaxInfo { name: "WHERE_KW" },
            PUBLIC_KW => &SyntaxInfo { name: "PUBLIC_KW" },
            INTERNAL_KW => &SyntaxInfo { name: "INTERNAL_KW" },
            ROOT_KW => &SyntaxInfo { name: "ROOT_KW" },
            SUPER_KW => &SyntaxInfo { name: "SUPER_KW" },
            SELF_KW => &SyntaxInfo { name: "SELF_KW" },
            MATCH_KW => &SyntaxInfo { name: "MATCH_KW" },
            COMPTIME_KW => &SyntaxInfo { name: "COMPTIME_KW" },
            MACRO_KW => &SyntaxInfo { name: "MACRO_KW" },
            EFFECT_KW => &SyntaxInfo { name: "EFFECT_KW" },
            USES_KW => &SyntaxInfo { name: "USES_KW" },
            PERFORM_KW => &SyntaxInfo { name: "PERFORM_KW" },
            HANDLE_KW => &SyntaxInfo { name: "HANDLE_KW" },
            RESUME_KW => &SyntaxInfo { name: "RESUME_KW" },
            EXTERN_KW => &SyntaxInfo { name: "EXTERN_KW" },
            SUPERVISOR_KW => &SyntaxInfo { name: "SUPERVISOR_KW" },
            CHILD_KW => &SyntaxInfo { name: "CHILD_KW" },
            SPAWN_KW => &SyntaxInfo { name: "SPAWN_KW" },
            CONSUMING_KW => &SyntaxInfo { name: "CONSUMING_KW" },
            BORROWING_KW => &SyntaxInfo { name: "BORROWING_KW" },
            INOUT_KW => &SyntaxInfo { name: "INOUT_KW" },
            READ_KW => &SyntaxInfo { name: "READ_KW" },
            OUT_KW => &SyntaxInfo { name: "OUT_KW" },
            MUT_KW => &SyntaxInfo { name: "MUT_KW" },
            DEF_KW => &SyntaxInfo { name: "DEF_KW" },
            DATA_KW => &SyntaxInfo { name: "DATA_KW" },
            INT_NUMBER => &SyntaxInfo { name: "INT_NUMBER" },
            FLOAT_NUMBER => &SyntaxInfo { name: "FLOAT_NUMBER" },
            STRING => &SyntaxInfo { name: "STRING" },
            ERROR => &SyntaxInfo { name: "ERROR" },
            IDENT => &SyntaxInfo { name: "IDENT" },
            INDEX => &SyntaxInfo { name: "INDEX" },
            WHITESPACE => &SyntaxInfo { name: "WHITESPACE" },
            COMMENT => &SyntaxInfo { name: "COMMENT" },
            SOURCE_FILE => &SyntaxInfo { name: "SOURCE_FILE" },
            ATTRIBUTE_LIST => &SyntaxInfo { name: "ATTRIBUTE_LIST" },
            ATTRIBUTE => &SyntaxInfo { name: "ATTRIBUTE" },
            FUNCTION_DEF => &SyntaxInfo { name: "FUNCTION_DEF" },
            EXTERN => &SyntaxInfo { name: "EXTERN" },
            RET_TYPE => &SyntaxInfo { name: "RET_TYPE" },
            VISIBILITY => &SyntaxInfo { name: "VISIBILITY" },
            USES_CLAUSE => &SyntaxInfo { name: "USES_CLAUSE" },
            PARAM_LIST => &SyntaxInfo { name: "PARAM_LIST" },
            PARAM => &SyntaxInfo { name: "PARAM" },
            SELF_PARAM => &SyntaxInfo { name: "SELF_PARAM" },
            GENERIC_PARAM_LIST => &SyntaxInfo { name: "GENERIC_PARAM_LIST" },
            GENERIC_PARAM => &SyntaxInfo { name: "GENERIC_PARAM" },
            GENERIC_ARG_LIST => &SyntaxInfo { name: "GENERIC_ARG_LIST" },
            WHERE_CLAUSE => &SyntaxInfo { name: "WHERE_CLAUSE" },
            WHERE_PRED => &SyntaxInfo { name: "WHERE_PRED" },
            INHERITANCE_LIST => &SyntaxInfo { name: "INHERITANCE_LIST" },
            STRUCT_DEF => &SyntaxInfo { name: "STRUCT_DEF" },
            TYPE_ALIAS_DEF => &SyntaxInfo { name: "TYPE_ALIAS_DEF" },
            CONST_DEF => &SyntaxInfo { name: "CONST_DEF" },
            RECORD_FIELD_DEF_LIST => &SyntaxInfo { name: "RECORD_FIELD_DEF_LIST" },
            RECORD_FIELD_DEF => &SyntaxInfo { name: "RECORD_FIELD_DEF" },
            TUPLE_FIELD_DEF_LIST => &SyntaxInfo { name: "TUPLE_FIELD_DEF_LIST" },
            TUPLE_FIELD_DEF => &SyntaxInfo { name: "TUPLE_FIELD_DEF" },
            TRAIT_DEF => &SyntaxInfo { name: "TRAIT_DEF" },
            ENUM_DEF => &SyntaxInfo { name: "ENUM_DEF" },
            ENUM_VARIANT_LIST => &SyntaxInfo { name: "ENUM_VARIANT_LIST" },
            ENUM_VARIANT => &SyntaxInfo { name: "ENUM_VARIANT" },
            EFFECT_DEF => &SyntaxInfo { name: "EFFECT_DEF" },
            EFFECT_OP_LIST => &SyntaxInfo { name: "EFFECT_OP_LIST" },
            EFFECT_OP => &SyntaxInfo { name: "EFFECT_OP" },
            MACRO_DEF => &SyntaxInfo { name: "MACRO_DEF" },
            PATH_TYPE => &SyntaxInfo { name: "PATH_TYPE" },
            ARRAY_TYPE => &SyntaxInfo { name: "ARRAY_TYPE" },
            TUPLE_TYPE => &SyntaxInfo { name: "TUPLE_TYPE" },
            PAREN_TYPE => &SyntaxInfo { name: "PAREN_TYPE" },
            REFERENCE_TYPE => &SyntaxInfo { name: "REFERENCE_TYPE" },
            FUNCTION_TYPE => &SyntaxInfo { name: "FUNCTION_TYPE" },
            VARIADIC_TYPE => &SyntaxInfo { name: "VARIADIC_TYPE" },
            NEVER_TYPE => &SyntaxInfo { name: "NEVER_TYPE" },
            OPTIONAL_TYPE => &SyntaxInfo { name: "OPTIONAL_TYPE" },
            REFINEMENT_TYPE => &SyntaxInfo { name: "REFINEMENT_TYPE" },
            SUPERVISOR_DEF => &SyntaxInfo { name: "SUPERVISOR_DEF" },
            SUPERVISOR_ITEM_LIST => &SyntaxInfo { name: "SUPERVISOR_ITEM_LIST" },
            SUPERVISOR_ENTRY => &SyntaxInfo { name: "SUPERVISOR_ENTRY" },
            CHILD_DEF => &SyntaxInfo { name: "CHILD_DEF" },
            LET_STMT => &SyntaxInfo { name: "LET_STMT" },
            EXPR_STMT => &SyntaxInfo { name: "EXPR_STMT" },
            PATH_EXPR => &SyntaxInfo { name: "PATH_EXPR" },
            PREFIX_EXPR => &SyntaxInfo { name: "PREFIX_EXPR" },
            LITERAL => &SyntaxInfo { name: "LITERAL" },
            BIN_EXPR => &SyntaxInfo { name: "BIN_EXPR" },
            CAST_EXPR => &SyntaxInfo { name: "CAST_EXPR" },
            PAREN_EXPR => &SyntaxInfo { name: "PAREN_EXPR" },
            CALL_EXPR => &SyntaxInfo { name: "CALL_EXPR" },
            METHOD_CALL_EXPR => &SyntaxInfo { name: "METHOD_CALL_EXPR" },
            FIELD_EXPR => &SyntaxInfo { name: "FIELD_EXPR" },
            IF_EXPR => &SyntaxInfo { name: "IF_EXPR" },
            INDEX_EXPR => &SyntaxInfo { name: "INDEX_EXPR" },
            BLOCK_EXPR => &SyntaxInfo { name: "BLOCK_EXPR" },
            RETURN_EXPR => &SyntaxInfo { name: "RETURN_EXPR" },
            WHILE_EXPR => &SyntaxInfo { name: "WHILE_EXPR" },
            LOOP_EXPR => &SyntaxInfo { name: "LOOP_EXPR" },
            BREAK_EXPR => &SyntaxInfo { name: "BREAK_EXPR" },
            ARRAY_EXPR => &SyntaxInfo { name: "ARRAY_EXPR" },
            TUPLE_EXPR => &SyntaxInfo { name: "TUPLE_EXPR" },
            CLOSURE_EXPR => &SyntaxInfo { name: "CLOSURE_EXPR" },
            CONDITION => &SyntaxInfo { name: "CONDITION" },
            COMPTIME_EXPR => &SyntaxInfo { name: "COMPTIME_EXPR" },
            MATCH_EXPR => &SyntaxInfo { name: "MATCH_EXPR" },
            MATCH_ARM_LIST => &SyntaxInfo { name: "MATCH_ARM_LIST" },
            MATCH_ARM => &SyntaxInfo { name: "MATCH_ARM" },
            PERFORM_EXPR => &SyntaxInfo { name: "PERFORM_EXPR" },
            SPAWN_EXPR => &SyntaxInfo { name: "SPAWN_EXPR" },
            HANDLE_EXPR => &SyntaxInfo { name: "HANDLE_EXPR" },
            HANDLER_ARM_LIST => &SyntaxInfo { name: "HANDLER_ARM_LIST" },
            HANDLER_ARM => &SyntaxInfo { name: "HANDLER_ARM" },
            TRY_EXPR => &SyntaxInfo { name: "TRY_EXPR" },
            TRANSFER_EXPR => &SyntaxInfo { name: "TRANSFER_EXPR" },
            CHANNEL_RECV_EXPR => &SyntaxInfo { name: "CHANNEL_RECV_EXPR" },
            CHANNEL_SEND_EXPR => &SyntaxInfo { name: "CHANNEL_SEND_EXPR" },
            BIND_PAT => &SyntaxInfo { name: "BIND_PAT" },
            PLACEHOLDER_PAT => &SyntaxInfo { name: "PLACEHOLDER_PAT" },
            LITERAL_PAT => &SyntaxInfo { name: "LITERAL_PAT" },
            PATH_PAT => &SyntaxInfo { name: "PATH_PAT" },
            TUPLE_STRUCT_PAT => &SyntaxInfo { name: "TUPLE_STRUCT_PAT" },
            TUPLE_PAT => &SyntaxInfo { name: "TUPLE_PAT" },
            PAREN_PAT => &SyntaxInfo { name: "PAREN_PAT" },
            ARG_LIST => &SyntaxInfo { name: "ARG_LIST" },
            NAME => &SyntaxInfo { name: "NAME" },
            NAME_REF => &SyntaxInfo { name: "NAME_REF" },
            PATH => &SyntaxInfo { name: "PATH" },
            PATH_SEGMENT => &SyntaxInfo { name: "PATH_SEGMENT" },
            RECORD_LIT => &SyntaxInfo { name: "RECORD_LIT" },
            RECORD_FIELD_LIST => &SyntaxInfo { name: "RECORD_FIELD_LIST" },
            RECORD_FIELD => &SyntaxInfo { name: "RECORD_FIELD" },
            USE => &SyntaxInfo { name: "USE" },
            USE_TREE => &SyntaxInfo { name: "USE_TREE" },
            USE_TREE_LIST => &SyntaxInfo { name: "USE_TREE_LIST" },
            RENAME => &SyntaxInfo { name: "RENAME" },
            EXTEND => &SyntaxInfo { name: "EXTEND" },
            EXTEND_ITEM_LIST => &SyntaxInfo { name: "EXTEND_ITEM_LIST" },
            EXTEND_ITEM => &SyntaxInfo { name: "EXTEND_ITEM" },
            EXTERN_BLOCK => &SyntaxInfo { name: "EXTERN_BLOCK" },
            EXTERN_ITEM_LIST => &SyntaxInfo { name: "EXTERN_ITEM_LIST" },
            EXTERN_ITEM => &SyntaxInfo { name: "EXTERN_ITEM" },
            TOMBSTONE => &SyntaxInfo { name: "TOMBSTONE" },
            EOF => &SyntaxInfo { name: "EOF" },
            __LAST => &SyntaxInfo { name: "__LAST" },
        }
    }

    pub fn from_keyword(ident: &str) -> Option<SyntaxKind> {
        let kw = match ident {
            "break" => BREAK_KW,
            "do" => DO_KW,
            "else" => ELSE_KW,
            "false" => FALSE_KW,
            "for" => FOR_KW,
            "func" => FUNC_KW,
            "if" => IF_KW,
            "in" => IN_KW,
            "as" => AS_KW,
            "import" => IMPORT_KW,
            "nil" => NIL_KW,
            "return" => RETURN_KW,
            "true" => TRUE_KW,
            "while" => WHILE_KW,
            "loop" => LOOP_KW,
            "let" => LET_KW,
            "var" => VAR_KW,
            "static" => STATIC_KW,
            "init" => INIT_KW,
            "override" => OVERRIDE_KW,
            "class" => CLASS_KW,
            "struct" => STRUCT_KW,
            "trait" => TRAIT_KW,
            "extend" => EXTEND_KW,
            "enum" => ENUM_KW,
            "never" => NEVER_KW,
            "type" => TYPE_KW,
            "where" => WHERE_KW,
            "public" => PUBLIC_KW,
            "internal" => INTERNAL_KW,
            "root" => ROOT_KW,
            "super" => SUPER_KW,
            "self" => SELF_KW,
            "match" => MATCH_KW,
            "comptime" => COMPTIME_KW,
            "macro" => MACRO_KW,
            "effect" => EFFECT_KW,
            "uses" => USES_KW,
            "perform" => PERFORM_KW,
            "handle" => HANDLE_KW,
            "resume" => RESUME_KW,
            "extern" => EXTERN_KW,
            "supervisor" => SUPERVISOR_KW,
            "child" => CHILD_KW,
            "spawn" => SPAWN_KW,
            _ => return None,
        };
        Some(kw)
    }

    pub fn from_char(c: char) -> Option<SyntaxKind> {
        let tok = match c {
            '&' => AMP,
            '|' => PIPE,
            '+' => PLUS,
            '-' => MINUS,
            '*' => STAR,
            '/' => SLASH,
            '%' => PERCENT,
            '^' => CARET,
            '#' => HASH,
            '.' => DOT,
            '<' => LT,
            '>' => GT,
            '=' => EQ,
            '(' => L_PAREN,
            ')' => R_PAREN,
            '{' => L_CURLY,
            '}' => R_CURLY,
            '[' => L_BRACKET,
            ']' => R_BRACKET,
            ';' => SEMI,
            ':' => COLON,
            ',' => COMMA,
            '!' => EXCLAMATION,
            '?' => QUESTION,
            '@' => AT,
            '~' => TILDE,
            '_' => UNDERSCORE,
            _ => return None,
        };
        Some(tok)
    }
}
