[package]
name = "codira_hir"
description = "Provides high-level intermediate representation of Codira code"
keywords = ["game", "hot-reloading", "language", "codira", "scripting"]
categories.workspace = true
version.workspace = true
authors.workspace = true
edition.workspace = true
documentation.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
la-arena = { workspace = true }
codira_syntax = { version = "0.6.0-dev", path = "../codira_syntax" }
codira_target = { version = "0.6.0-dev", path = "../codira_target" }
codira_paths = { version = "0.6.0-dev", path="../codira_paths" }
codira_hir_input = { version = "0.6.0-dev", path="../codira_hir_input" }
codira_mir = { version = "0.6.0-dev", path = "../codira_mir" }
codira_comptime = { version = "0.6.0-dev", path = "../codira_comptime" }
codira_smt = { version = "0.6.0-dev", path = "../codira_smt" }
drop_bomb = { workspace = true }
either = { workspace = true }
ena = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
rustc-hash = { workspace = true }
salsa = { workspace = true }
smallvec = { workspace = true, features = ["union"] }
bitflags = { workspace = true }
smol_str = { workspace = true }

[dev-dependencies]
codira_test = { path = "../codira_test" }
insta = { workspace = true }
parking_lot = { workspace = true }
text_trees = { workspace = true }
